### ISSUE TITLE
when i am calling getCurrentNetworkTime() getting this exception

### ISSUE THREAD

**Issue by subbumelzol** [AndroidDevLog/NetworkTimeProtocol#1]
android.os.NetworkOnMainThreadException
12-16 18:51:55.061 3641-3641/ W/System.err:     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
12-16 18:51:55.061 3641-3641/ W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
12-16 18:51:55.061 3641-3641/ W/System.err:     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
12-16 18:51:55.061 3641-3641/ W/System.err:     at java.net.InetAddress.getByName(InetAddress.java:305)

**Comment by jiaxianhua** [comment]
@subbumelzol do you use it in the main thread. Your should use in a new thread. Try to do it like my code in *MainActivity.java*. Or put the code here, I try to fix it.

```
public class MainActivity extends AppCompatActivity {
    private TextView timeTextView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        timeTextView = (TextView) findViewById(R.id.time_textview);

        Button button = (Button) findViewById(R.id.get_network_time_button);
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        final long networkTime = Util.getCurrentNetworkTime();
                        runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                Date date = new Date();
                                if (networkTime > 0) {
                                    date = new Date(networkTime);
                                    Toast.makeText(MainActivity.this, "get network time success",
                                            Toast.LENGTH_SHORT).show();
                                } else {
                                    Toast.makeText(MainActivity.this, "get network time failed, use local time",
                                            Toast.LENGTH_SHORT).show();
                                }

                                SimpleDateFormat simpleFormatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                                String text = simpleFormatter.format(date);
                                timeTextView.setText(text);
                            }
                        });
                    }
                }).start();
            }
        });
    }
}
```
